# Generated by Django 3.2.5 on 2021-07-24 18:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('dead', models.BooleanField(default=False, editable=False)),
                ('fetched', models.BooleanField(default=False, editable=False)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('poll', 'Poll'), ('pollopt', 'Poll option'), ('comment', 'Comment')], editable=False, max_length=10)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='News.base')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('score', models.IntegerField()),
            ],
            options={
                'ordering': ['-time_created'],
            },
            bases=('News.base',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='News.base')),
                ('title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('descendants', models.IntegerField(null=True)),
                ('text', models.TextField()),
            ],
            bases=('News.base',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('newsitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='News.newsitem')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            bases=('News.newsitem',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('newsitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='News.newsitem')),
                ('descendants', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
            bases=('News.newsitem',),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='News.base')),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pollOptions', to='News.base')),
            ],
            bases=('News.base',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='News.base')),
                ('text', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='News.base')),
            ],
            bases=('News.base',),
        ),
    ]
